"""remove_share_with_supervisors_field

Revision ID: 4325d5347887
Revises: 949bf4151ea6
Create Date: 2025-07-20 19:36:54.075376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4325d5347887'
down_revision: Union[str, Sequence[str], None] = '949bf4151ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stress_scores', 'share_with_supervisors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stress_scores', sa.Column('share_with_supervisors', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
