"""update_booking_system_for_30min_sessions

Revision ID: 482dda2293cb
Revises: 50a40f6d8ab7
Create Date: 2025-07-26 16:53:27.213221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '482dda2293cb'
down_revision: Union[str, Sequence[str], None] = '50a40f6d8ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultant_bookings', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultant_bookings', 'rejection_reason')
    # ### end Alembic commands ###
