"""modify_registration_number_constraint

Revision ID: 50a40f6d8ab7
Revises: 5ad604c929b9
Create Date: 2025-07-24 13:25:51.172081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a40f6d8ab7'
down_revision: Union[str, Sequence[str], None] = '5ad604c929b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop and recreate the unique constraint on registration_number to allow NULL values
    # MySQL allows multiple NULL values in a unique constraint
    op.execute("ALTER TABLE user_registration_requests DROP INDEX registration_number")
    op.execute("ALTER TABLE user_registration_requests ADD UNIQUE (registration_number)")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # This is the same operation, so no change needed for downgrade
    pass
    
    # ### end Alembic commands ###
