"""cleanup_empty_registration_numbers

Revision ID: 5ad604c929b9
Revises: 4325d5347887
Create Date: 2025-07-24 13:25:25.934003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad604c929b9'
down_revision: Union[str, Sequence[str], None] = '4325d5347887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Clean up empty registration numbers by setting them to NULL
    op.execute("UPDATE user_registration_requests SET registration_number = NULL WHERE registration_number = '' OR registration_number IS NULL")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
