"""add_assigned_date_and_duration_to_tasks

Revision ID: 7bc30fb01f16
Revises: 72bb3c0cb774
Create Date: 2025-08-10 23:16:45.962599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7bc30fb01f16'
down_revision: Union[str, Sequence[str], None] = '72bb3c0cb774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consultant_bookings', 'status',
               existing_type=mysql.ENUM('pending', 'approved', 'rejected', 'completed', 'cancelled'),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    
    # Add assigned_date column as nullable first
    op.add_column('tasks', sa.Column('assigned_date', sa.DateTime(), nullable=True))
    
    # Update existing tasks to have assigned_date = created_at
    op.execute("UPDATE tasks SET assigned_date = created_at WHERE assigned_date IS NULL")
    
    # Now make assigned_date non-nullable
    op.alter_column('tasks', 'assigned_date', nullable=False)
    
    # Add duration column
    op.add_column('tasks', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'duration')
    op.drop_column('tasks', 'assigned_date')
    op.alter_column('consultant_bookings', 'status',
               existing_type=mysql.ENUM('pending', 'approved', 'rejected', 'completed', 'cancelled'),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    # ### end Alembic commands ###
