"""add_share_with_supervisors_field

Revision ID: 949bf4151ea6
Revises: 58665e92610f
Create Date: 2025-07-20 19:29:29.854278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949bf4151ea6'
down_revision: Union[str, Sequence[str], None] = '58665e92610f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stress_scores', sa.Column('share_with_supervisors', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stress_scores', 'share_with_supervisors')
    # ### end Alembic commands ###
