"""update_stress_score_model

Revision ID: e6e40c1faee7
Revises: f831e1e43bb7
Create Date: 2025-07-20 18:12:46.480249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e6e40c1faee7'
down_revision: Union[str, Sequence[str], None] = 'f831e1e43bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stress_scores', sa.Column('level', sa.String(length=20), nullable=False))
    op.add_column('stress_scores', sa.Column('share_with_supervisor', sa.Boolean(), nullable=True))
    op.add_column('stress_scores', sa.Column('share_with_hr', sa.Boolean(), nullable=True))
    op.add_column('stress_scores', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('stress_scores', 'employee_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('stress_scores', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stress_scores', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('stress_scores', 'employee_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('stress_scores', 'updated_at')
    op.drop_column('stress_scores', 'share_with_hr')
    op.drop_column('stress_scores', 'share_with_supervisor')
    op.drop_column('stress_scores', 'level')
    # ### end Alembic commands ###
